# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPC-Simple
version:      1.002
version_from: Simple.pm
installdirs:  site
requires:
    Data::Dumper:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
